sudo: required

git:
  depth: 3

services:
  - docker

install:
  - docker build --file Dockerfile.py3 --tag guillaume-florent/ccad-py3:latest .
  - docker build --file Dockerfile.py2 --tag guillaume-florent/ccad-py2:latest .

#  A job fails if the return code of the script phase is non zero.
script:
  - docker run guillaume-florent/ccad-py3:latest /bin/bash -c "cd /opt/ccad/unittest;python -m unittest test_all"
  - docker run guillaume-florent/ccad-py2:latest /bin/bash -c "cd /opt/ccad/unittest;python -m unittest test_all"

after_script:
  - docker images