package:
  name: ccad
  version: "0.3.0"

source:
  path: ../ccad

build:
  number: 0
  noarch: python
  script: python setup.py install
  include_recipe: True

requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - matplotlib
    - wxpython>=4
    - pyqt >=5
    # - pythonocc-core ==0.18.2

about:
  home: https://github.com/osv-team/ccad
  license: GPLv3
  license_file: LICENSE
  summary: PythonOCC wrapper